services:
  flask-app:
    image: acrmycontainer01.azurecr.io/two-tier-flask:v1
    container_name: flask-appdb
    ports:
      - "5001:5000"
    networks:
      - two-tier
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: testdb
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8
    container_name: mysql_flask
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./message.sql:/docker-entrypoint-initdb.d/message.sql

    networks:
      - two-tier

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  two-tier:
volumes:
  mysql-data:


# version: "3.8"

# services:
#   mysql:
#     user: "${UID}:${GID}" 
#     image: mysql:5.7
#     container_name: mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: devops
#       MYSQL_USER: admin
#       MYSQL_PASSWORD: admin
#     volumes:
#       - ./mysql-data:/var/lib/mysql
#       - ./message.sql:/docker-entrypoint-initdb.d/message.sql  
#     networks:
#       - twotier
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
#       start_period: 60s

#   flask-app:
#     image: trainwithshubham/two-tier-flask-app:latest
#     container_name: flask-app
#     ports:
#       - "5000:5000"
#     environment:
#       MYSQL_HOST: mysql
#       MYSQL_USER: root
#       MYSQL_PASSWORD: root
#       MYSQL_DB: devops
#     depends_on:
#       - mysql
#     networks:
#       - twotier
#     restart: always
#     healthcheck:
#       test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
#       start_period: 30s

# networks:
#   twotier:
